@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json; charset=utf-8

{
  "name": "franco",
  "email": "franco@gmail.com",
  "password": "12345"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "franco@gmail.com",
  "password": "12345"
}

###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Nova pergunta 4",
  "content": "Conteúdo da pergunta"
}

###

# @name fetch_recent_questions
GET {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name create_patients
POST {{baseUrl}}/patients
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "email": "patient1@gmail.com", 
  "name": "patient name", 
  "password": "123456", 
  "confirmPassword": "123456", 
  "attachments": []
}

###

# @name fetch_patients
GET {{baseUrl}}/patients?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name edit_patients
PUT {{baseUrl}}/patients/071bd12f-8ac0-41c9-9dba-0b43f326eabe
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "email": "patient10@gmail.com", 
  "name": "patient name12", 
  "password": "1234567", 
  "confirmPassword": "1234567", 
  "attachments": []
}

###

# @name delete_patients
DELETE {{baseUrl}}/patients/071bd12f-8ac0-41c9-9dba-0b43f326eabe
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name create_employees
POST {{baseUrl}}/employees
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "email": "patient12@gmail.com", 
  "name": "employename12", 
  "password": "123456", 
  "confirmPassword": "123456", 
  "department": "cuidador",
  "role": "role"
}

###

# @name fetch_employees
GET {{baseUrl}}/employees?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name delete_employees
DELETE {{baseUrl}}/employees/233a6d22-0452-4de9-bf01-f16a0526558e
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name edit_employees
PUT {{baseUrl}}/employees/2472f50e-3413-4a84-85a5-981c3d782b89
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "department": "medico", 
  "email": "teste@test.com", 
  "name": "testei", 
  "password": "123456", 
  "role": "gerente"
}

###

# @name create_employees
POST {{baseUrl}}/alternate-days-scheduling
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "address": "rua z",
  "closingContractTimeStamp": 1704213000000,
  "startContractTimeStamp": 1704126600000,
  "startHours": "15:00",
  "closingHours": "16:00",
  "employeeId": "1",
  "patientId": "2",
  "hoursOfServicePerConsultation": 24,
  "hoursOfSpacingPerConsultation": 12 ,
  "scheduledDaysWeek": [
    "Monday"
  ]
}
